// Generated by Wrangler on Wed Jul 24 2024 17:20:47 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	googleSheetsOAuthStore: KVNamespace;
	CLIENT_ID: string;
	CLIENT_SECRET: string;
	PLUGIN_URI: string;
	REDIRECT_URI: string;
	AUTHORIZE_ENDPOINT: string;
	TOKEN_ENDPOINT: string;
	SCOPE: string;
}
