#:schema node_modules/wrangler/config-schema.json
name = "framer-google-sheets-oauth"
main = "src/index.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "googleSheetsOAuthStore"
id = "f8fc6a096d7f445fb1d0b8fb155a3b8b"
